#!/usr/bin/env bash
# MIT © Sindre Sorhus - sindresorhus.com

# git hook to run a command after `git pull` if a specified file was changed
# Installation steps:
# 1. Rename to `post-merge`
# 2. Copy into $PROJECT_DIR/.git/hooks
# 3. Rename to `post-merge`

changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

check_run() {
  echo "$changed_files" | grep --quiet "$1" && eval "$2"
}

check_run package.json "yarn"
